-- -- import lspsaga safely
-- local saga_status, saga = pcall(require, "lspsaga")
-- if not saga_status then
-- 	return
-- end
--
-- saga.init_lsp_saga({
-- 	-- keybinds for navigation in lspsaga window
-- 	move_in_saga = { prev = "<C-k>", next = "<C-j>" },
-- 	-- use enter to open file with finder
-- 	finder_action_keys = {
-- 		open = "<CR>",
-- 	},
-- 	-- use enter to open file with definition preview
-- 	definition_action_keys = {
-- 		edit = "<CR>",
-- 	},
-- })
--
-- require("lazy").setup({
--     "glepnir/lspsaga.nvim",
--     event = "LspAttach",
--     config = function()
--       require("lspsaga").setup({})
--     end,
--     dependencies = { {"nvim-tree/nvim-web-devicons"} }
-- })
--
-- require("lspsaga").setup({
--   preview = {
--     lines_above = 0,
--     lines_below = 10,
--   },
--   scroll_preview = {
--     scroll_down = "<C-f>",
--     scroll_up = "<C-b>",
--   },
--   request_timeout = 2000,
--
--   -- See Customizing Lspsaga's Appearance
--   ui = { ... },
--
--   -- For default options for each command, see below
--   finder = { ... },
--   code_action = { ... }
--   -- etc.
-- })
